export * from './Landing';
export * from './BusinessSelect';
export * from './Home';
export * from './People';
export * from './Money';
export * from './Staff';
export * from './Settings';
export { default as Landing } from './Landing';
export { default as BusinessSelect } from './BusinessSelect';
export { default as Home } from './Home';
export { default as People } from './People';
export { default as Money } from './Money';
export { default as Staff } from './Staff';
export { default as Settings } from './Settings';
export { default as AddTenantPG } from './AddTenantPG';
export { default as AddMemberGym } from './AddMemberGym';
export { default as AddSubscriberTiffin } from './AddSubscriberTiffin';
export { default as BillGenerator } from './BillGenerator';
export { default as Attendance } from './Attendance';